/**
 * Railway Maintenance Operations — shared UI primitives.
 *
 * Geometry: 0px on tables/timelines, 2px on controls, 4px on panels/modals.
 * Structure comes from borders and spacing; shadows appear on overlays only.
 * Mono is reserved for IDs, timestamps, minutes and counts — never prose.
 */
import React from 'react';
import { AlertTriangle, Info, CheckCircle2, XCircle } from 'lucide-react';

/* ------------------------------------------------------------------ tones */

export const TONES = {
  critical: { text: 'text-status-critical', bg: 'bg-status-critical-tint', border: 'border-status-critical', solid: 'bg-status-critical' },
  warn: { text: 'text-status-warn', bg: 'bg-status-warn-tint', border: 'border-status-warn', solid: 'bg-status-warn' },
  ok: { text: 'text-status-ok', bg: 'bg-status-ok-tint', border: 'border-status-ok', solid: 'bg-status-ok' },
  info: { text: 'text-status-info', bg: 'bg-status-info-tint', border: 'border-status-info', solid: 'bg-status-info' },
  idle: { text: 'text-status-idle', bg: 'bg-status-idle-tint', border: 'border-line-strong', solid: 'bg-status-idle' },
  bundle: { text: 'text-bundle', bg: 'bg-bundle-tint', border: 'border-bundle', solid: 'bg-bundle' },
};
const tone = (t) => TONES[t] || TONES.idle;

/* ------------------------------------------------------------------ Panel */

export const Panel = ({ children, className = '', flush = false }) => (
  <div className={`bg-surface-panel border border-line rounded-lg ${className}`}>
    {flush ? children : children}
  </div>
);

export const PanelHeader = ({ title, scope, action, children }) => (
  <div className="px-3 py-2.5 bg-surface-sunken border-b border-line flex items-start justify-between gap-3 rounded-t-lg">
    <div className="min-w-0">
      <div className="t-label">{title}</div>
      {scope && <div className="t-scope mt-0.5 normal-case tracking-normal">{scope}</div>}
      {children}
    </div>
    {action && <div className="shrink-0">{action}</div>}
  </div>
);

export const PanelBody = ({ children, className = '' }) => (
  <div className={`p-3 ${className}`}>{children}</div>
);

/* ------------------------------------------------------- Scope + provenance */

/** Attaches the artifact scope to a figure so demo-subset and full-run
 *  numbers can never be read as the same claim. */
export const ScopeCaption = ({ children, className = '' }) => (
  <span className={`t-scope ${className}`}>{children}</span>
);

/**
 * Technical provenance, verbatim from the artifact. Engine names survive here
 * because they are true statements about how a file was produced — never as a
 * heading, nav label, or feature name.
 */
export const ProvenanceNote = ({ generatedBy, command, dataset, note, defaultOpen = false }) => (
  <details className="group" open={defaultOpen}>
    <summary className="t-scope cursor-pointer select-none hover:text-rail-500 list-none flex items-center gap-1">
      <span className="inline-block transition-transform group-open:rotate-90">›</span>
      Generated by / reproduce with
    </summary>
    <div className="mt-1.5 pl-3 border-l border-line space-y-1">
      {generatedBy && (
        <div className="font-mono text-[10px] text-rail-500 break-all">{generatedBy}</div>
      )}
      {command && (
        <div className="font-mono text-[10px] text-rail-500 break-all">$ {command}</div>
      )}
      {dataset && (
        <div className="font-mono text-[10px] text-rail-400 break-all">dataset: {dataset}</div>
      )}
      {note && <div className="text-[10px] text-rail-400 leading-relaxed">{note}</div>}
    </div>
  </details>
);

/* ------------------------------------------------------------------ status */

export const StatusDot = ({ tone: t = 'idle', size = 8, className = '' }) => (
  <span
    className={`inline-block rounded-full shrink-0 ${tone(t).solid} ${className}`}
    style={{ width: size, height: size }}
  />
);

export const StatusBadge = ({ tone: t = 'idle', children, size = 'md', className = '' }) => {
  const sizes = {
    sm: 'text-[9px] px-1.5 py-0.5',
    md: 'text-[10px] px-2 py-0.5',
    lg: 'text-[11px] px-2.5 py-1',
  };
  const c = tone(t);
  return (
    <span
      className={`inline-flex items-center gap-1 font-semibold uppercase tracking-wide border rounded-sm ${c.bg} ${c.text} ${c.border} ${sizes[size]} ${className}`}
    >
      {children}
    </span>
  );
};

/* ------------------------------------------------------------------ Metric */

export const Metric = ({ label, value, sub, tone: t, scope, mono = true, className = '' }) => (
  <div className={className}>
    <div className="t-label">{label}</div>
    <div className={`${mono ? 'font-mono' : ''} text-xl font-semibold mt-0.5 ${t ? tone(t).text : 'text-rail-900'}`}>
      {value}
    </div>
    {sub && <div className="text-[10px] text-rail-400 mt-0.5">{sub}</div>}
    {scope && <ScopeCaption className="block mt-1">{scope}</ScopeCaption>}
  </div>
);

/** Dense label/value row used inside summary panels. */
export const MetricRow = ({ label, value, sub, tone: t, onClick }) => {
  const Tag = onClick ? 'button' : 'div';
  return (
    <Tag
      onClick={onClick}
      className={`w-full text-left px-3 py-2 border-b border-line last:border-b-0 flex items-center justify-between gap-3 ${
        onClick ? 'hover:bg-surface-sunken transition-colors' : ''
      }`}
    >
      <span className="min-w-0">
        <span className="block text-xs font-medium text-rail-700">{label}</span>
        {sub && <span className="block text-[10px] text-rail-400 mt-0.5">{sub}</span>}
      </span>
      <span className={`font-mono text-sm font-bold shrink-0 ${t ? tone(t).text : 'text-rail-900'}`}>
        {value}
      </span>
    </Tag>
  );
};

/* ------------------------------------------------------------------ Button */

export const Button = ({
  variant = 'secondary', size = 'md', children, className = '', ...props
}) => {
  const variants = {
    primary: 'bg-status-info text-white border-status-info hover:bg-blue-700',
    secondary: 'bg-surface-panel text-rail-700 border-line hover:bg-surface-sunken',
    danger: 'bg-status-critical text-white border-status-critical hover:bg-red-800',
    warn: 'bg-status-warn-tint text-status-warn border-status-warn hover:bg-amber-100',
    ghost: 'bg-transparent text-rail-500 border-transparent hover:bg-surface-sunken',
  };
  const sizes = {
    sm: 'text-[11px] px-2 py-1',
    md: 'text-xs px-3 py-1.5',
    // Ground portal: 44px minimum touch target.
    lg: 'text-sm px-5 py-3 min-h-touch',
  };
  return (
    <button
      className={`inline-flex items-center justify-center gap-1.5 font-semibold border rounded-sm transition-colors disabled:opacity-40 disabled:cursor-not-allowed ${variants[variant]} ${sizes[size]} ${className}`}
      {...props}
    >
      {children}
    </button>
  );
};

/* -------------------------------------------------------------------- Tabs */

export const Tabs = ({ items, value, onChange, className = '' }) => (
  <div className={`flex items-stretch border-b border-line ${className}`}>
    {items.map((it) => {
      const active = it.id === value;
      return (
        <button
          key={it.id}
          onClick={() => onChange(it.id)}
          className={`px-4 py-2.5 text-xs font-semibold tracking-wide border-b-2 -mb-px transition-colors ${
            active
              ? 'border-status-info text-rail-900'
              : 'border-transparent text-rail-500 hover:text-rail-700'
          }`}
        >
          {it.label}
          {it.count != null && (
            <span className="ml-1.5 font-mono text-[10px] text-rail-400">{it.count}</span>
          )}
        </button>
      );
    })}
  </div>
);

/* --------------------------------------------------------------- FilterBar */

export const FilterBar = ({ children, className = '' }) => (
  <div className={`bg-surface-panel border border-line rounded-lg px-3 py-2.5 flex flex-wrap items-center gap-2.5 ${className}`}>
    {children}
  </div>
);

export const Select = ({ label, className = '', ...props }) => (
  <label className="inline-flex items-center gap-1.5">
    {label && <span className="t-label">{label}</span>}
    <select
      className={`text-xs bg-surface-panel border border-line rounded-sm px-2 py-1.5 font-medium text-rail-700 focus:outline-none focus:ring-1 focus:ring-status-info ${className}`}
      {...props}
    />
  </label>
);

export const TextInput = ({ className = '', ...props }) => (
  <input
    className={`text-xs bg-surface-panel border border-line rounded-sm px-2.5 py-1.5 text-rail-900 placeholder:text-rail-400 focus:outline-none focus:ring-1 focus:ring-status-info ${className}`}
    {...props}
  />
);

/* ------------------------------------------------------------------- Alert */

const ALERT_ICON = { critical: XCircle, warn: AlertTriangle, ok: CheckCircle2, info: Info, idle: Info };

export const Alert = ({ tone: t = 'info', title, children, action, className = '' }) => {
  const c = tone(t);
  const Icon = ALERT_ICON[t] || Info;
  return (
    <div className={`${c.bg} border ${c.border} rounded-sm px-3 py-2.5 flex items-start gap-2.5 ${className}`}>
      <Icon size={15} className={`${c.text} shrink-0 mt-0.5`} />
      <div className="min-w-0 flex-1">
        {title && <div className={`text-xs font-bold ${c.text}`}>{title}</div>}
        {children && <div className="text-xs text-rail-700 mt-0.5 leading-relaxed">{children}</div>}
      </div>
      {action && <div className="shrink-0">{action}</div>}
    </div>
  );
};

/* -------------------------------------------------------------- EmptyState */

export const EmptyState = ({ title, children, className = '' }) => (
  <div className={`px-4 py-8 text-center ${className}`}>
    <div className="text-xs font-semibold text-rail-500">{title}</div>
    {children && (
      <div className="text-[11px] text-rail-400 mt-1 max-w-md mx-auto leading-relaxed">{children}</div>
    )}
  </div>
);

/**
 * Explicit data-boundary disclosure. Used where the dataset genuinely has no
 * column — never styled as an error, because the absence is the honest answer.
 */
export const NotAvailable = ({ label, reason }) => (
  <div className="px-3 py-2.5 border-b border-line last:border-b-0 flex items-center justify-between gap-3">
    <span className="min-w-0">
      <span className="block text-xs font-medium text-status-idle">{label}</span>
      {reason && <span className="block text-[10px] text-rail-400 mt-0.5">{reason}</span>}
    </span>
    <span className="text-[10px] font-semibold uppercase tracking-wide text-status-idle shrink-0">
      Not available
    </span>
  </div>
);

/* ---------------------------------------------------------------- Skeleton */

export const Skeleton = ({ className = '', rows = 3 }) => (
  <div className={`space-y-2 ${className}`}>
    {Array.from({ length: rows }).map((_, i) => (
      <div key={i} className="h-4 bg-surface-sunken rounded-sm animate-pulse" style={{ width: `${88 - i * 12}%` }} />
    ))}
  </div>
);

/* --------------------------------------------------------------- DataTable */

/**
 * Dense operational table. Flat geometry, border-separated, no zebra —
 * rows read as records, not as decoration.
 */
export const DataTable = ({
  columns, rows, getKey, onRowClick, rowClassName, dense = true, empty, className = '',
}) => (
  <div className={`overflow-x-auto custom-scrollbar ${className}`}>
    <table className="w-full text-left border-collapse text-xs">
      <thead className="bg-surface-sunken border-b border-line sticky top-0 z-10">
        <tr>
          {columns.map((c) => (
            <th
              key={c.key}
              className={`px-3 py-2 t-label whitespace-nowrap ${c.align === 'right' ? 'text-right' : ''} ${c.thClassName || ''}`}
              style={c.width ? { width: c.width } : undefined}
            >
              {c.header}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.length === 0 && (
          <tr>
            <td colSpan={columns.length}>
              {empty || <EmptyState title="No records match the current filters." />}
            </td>
          </tr>
        )}
        {rows.map((row) => (
          <tr
            key={getKey(row)}
            onClick={onRowClick ? () => onRowClick(row) : undefined}
            className={`border-b border-line-subtle last:border-b-0 ${
              onRowClick ? 'cursor-pointer hover:bg-status-info-tint/60' : ''
            } ${rowClassName ? rowClassName(row) : ''}`}
          >
            {columns.map((c) => (
              <td
                key={c.key}
                className={`px-3 ${dense ? 'py-1.5' : 'py-2'} align-middle ${c.align === 'right' ? 'text-right' : ''} ${c.tdClassName || ''}`}
              >
                {c.render ? c.render(row) : row[c.key]}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  </div>
);
