import React, { useState } from 'react';
import { usePlan } from '../../context/PlanContext';
import { Badge } from '../common/Badge';
import { CheckCircle2, XCircle, PencilLine, RefreshCw } from 'lucide-react';

const DECISION_VARIANT = {
  APPROVED: 'success',
  REJECTED: 'CRITICAL',
  MODIFIED: 'HIGH',
  RE_OPTIMIZED: 'primary',
};

/**
 * Controller actions on the optimizer's recommendation for one task.
 *
 * Approve / Modify / Reject record a decision in session state. Re-optimize
 * applies the replan the Python engine actually produced (replan_output/) --
 * the solver is not run in the browser, and the panel says so rather than
 * implying a live solve.
 */
export const RecommendationActions = ({ taskId = 'TASK-000005' }) => {
  const {
    planDecisions,
    approveRecommendation,
    rejectRecommendation,
    modifyRecommendation,
    reoptimize,
    isReplanned,
  } = usePlan();

  const [note, setNote] = useState('');
  const [noteFor, setNoteFor] = useState(null); // 'MODIFIED' | 'REJECTED' | null
  const decision = planDecisions[taskId];

  const submitNote = () => {
    if (noteFor === 'MODIFIED') modifyRecommendation(taskId, note);
    if (noteFor === 'REJECTED') rejectRecommendation(taskId, note);
    setNote('');
    setNoteFor(null);
  };

  return (
    <div className="bg-surface-panel border border-line rounded-lg p-4 space-y-3 ">
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div>
          <h3 className="text-xs font-bold uppercase tracking-wider text-rail-700">
            Controller Decision — {taskId}
          </h3>
          <p className="text-[11px] text-rail-500 mt-0.5">
            Accept, amend or reject the recommended possession. Decisions are held for this
            session only and are not sent to any external system.
          </p>
        </div>
        {decision && (
          <Badge variant={DECISION_VARIANT[decision.decision] || 'primary'} size="md">
            {decision.decision.replace('_', '-')} · {decision.decidedAt}
          </Badge>
        )}
      </div>

      <div className="flex flex-wrap gap-2">
        <button
          onClick={() => approveRecommendation(taskId)}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-status-ok text-white hover:bg-status-ok transition-colors"
        >
          <CheckCircle2 size={14} /> Approve Plan
        </button>
        <button
          onClick={() => setNoteFor('MODIFIED')}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-status-warn-tint text-status-warn border border-status-warn hover:bg-status-warn-tint transition-colors"
        >
          <PencilLine size={14} /> Request Modification
        </button>
        <button
          onClick={() => setNoteFor('REJECTED')}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-status-critical-tint text-status-critical border border-status-critical hover:bg-status-critical-tint transition-colors"
        >
          <XCircle size={14} /> Reject
        </button>
        <button
          onClick={() => reoptimize(taskId)}
          disabled={isReplanned}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-status-info text-white hover:bg-status-info disabled:bg-line disabled:text-rail-400 transition-colors"
          title="Applies the replan generated by optimizer.replan (replan_output/)"
        >
          <RefreshCw size={14} /> {isReplanned ? 'Replan Applied' : 'Re-optimize'}
        </button>
      </div>

      {noteFor && (
        <div className="border border-line rounded-lg p-3 space-y-2 bg-surface-sunken">
          <label className="text-[11px] font-semibold text-rail-600 block">
            Reason for {noteFor === 'MODIFIED' ? 'modification' : 'rejection'}
          </label>
          <textarea
            value={note}
            onChange={(e) => setNote(e.target.value)}
            rows={2}
            placeholder="e.g. crew reallocated to emergency work on adjacent section"
            className="w-full text-xs border border-line rounded-md px-2 py-1.5 focus:outline-hidden focus:ring-1 focus:ring-blue-500"
          />
          <div className="flex gap-2">
            <button
              onClick={submitNote}
              disabled={!note.trim()}
              className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-rail-900 text-white hover:bg-rail-700 disabled:bg-line disabled:text-rail-400"
            >
              Submit
            </button>
            <button
              onClick={() => { setNoteFor(null); setNote(''); }}
              className="px-3 py-1.5 rounded-lg text-xs font-semibold text-rail-600 hover:bg-line"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {decision?.note && (
        <p className="text-[11px] text-rail-600 bg-surface-sunken border border-line-subtle rounded-md px-2.5 py-1.5">
          <span className="font-semibold text-rail-500">Controller note:</span> {decision.note}
        </p>
      )}
    </div>
  );
};
